# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from hesap import intp


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(722, 175)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 701, 72))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.XlineEdit = QtWidgets.QLineEdit(self.widget)
        self.XlineEdit.setObjectName("XlineEdit")
        self.gridLayout.addWidget(self.XlineEdit, 0, 1, 2, 1)
        self.YlineEdit = QtWidgets.QLineEdit(self.widget)
        self.YlineEdit.setObjectName("YlineEdit")
        self.gridLayout.addWidget(self.YlineEdit, 2, 1, 1, 1)
        self.YLabel = QtWidgets.QLabel(self.widget)
        self.YLabel.setObjectName("YLabel")
        self.gridLayout.addWidget(self.YLabel, 2, 0, 1, 1)
        self.XLabel = QtWidgets.QLabel(self.widget)
        self.XLabel.setObjectName("XLabel")
        self.gridLayout.addWidget(self.XLabel, 0, 0, 2, 1)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(10, 90, 701, 34))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Alabel = QtWidgets.QLabel(self.widget1)
        self.Alabel.setObjectName("Alabel")
        self.gridLayout_2.addWidget(self.Alabel, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 3, 1, 1)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(10, 130, 278, 36))
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.XpushButton = QtWidgets.QPushButton(self.widget2)
        self.XpushButton.setObjectName("XpushButton")
        self.gridLayout_3.addWidget(self.XpushButton, 0, 0, 1, 1)
        self.YpushButton = QtWidgets.QPushButton(self.widget2)
        self.YpushButton.setObjectName("YpushButton")
        self.gridLayout_3.addWidget(self.YpushButton, 0, 1, 1, 1)
        self.CpushButton = QtWidgets.QPushButton(self.widget2)
        self.CpushButton.setObjectName("CpushButton")
        self.gridLayout_3.addWidget(self.CpushButton, 0, 2, 1, 1)

        self.retranslateUi(Form)
        self.CpushButton.clicked.connect(self.lineEdit_2.clear)
        self.CpushButton.clicked.connect(self.lineEdit.clear)
        self.CpushButton.clicked.connect(self.YlineEdit.clear)
        self.CpushButton.clicked.connect(self.XlineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.XpushButton.clicked.connect(self.xdegeral)
        self.YpushButton.clicked.connect(self.ydegeral)

    def xdegeral(self):
        x = list(self.XlineEdit.text().split(","))
        y = list(self.YlineEdit.text().split(","))
        q = float(self.lineEdit.text())
        sonuc = intp("x", x, y, q)
        self.lineEdit_2.setText(str(sonuc))

    def ydegeral(self):
        x = list(self.XlineEdit.text().split(","))
        y = list(self.YlineEdit.text().split(","))
        q = float(self.lineEdit.text())
        sonuc = intp("y", x, y, q)
        self.lineEdit_2.setText(str(sonuc))


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.YLabel.setText(_translate("Form", "Y:"))
        self.XLabel.setText(_translate("Form", "X:"))
        self.Alabel.setText(_translate("Form", "?:"))
        self.label.setText(_translate("Form", "Sonuç:"))
        self.XpushButton.setText(_translate("Form", "X"))
        self.YpushButton.setText(_translate("Form", "Y"))
        self.CpushButton.setText(_translate("Form", "Temizle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
